version: "3.8"

networks:
  app-net:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: npm run start
    volumes:
      - .:/app
      - ./app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - app-net

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: blog-pass
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/postgres
    restart: unless-stopped
    networks:
      - app-net

volumes:
  db-data:
