version: "3.8"

networks:
  app-net:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: blog-pass
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data/postgres
    restart: unless-stopped

volumes:
  db-data:
